### ISSUE TITLE
Remove __ngcc_lock_file__ before run compiler

### ISSUE THREAD

**Issue by peteichuk** [angular/ngcc-validation#1489]
Error: Timed.... -> "Another process, with id 28236, is currently running ngcc."

[temporary decision in stackoverflow](https://stackoverflow.com/questions/61122763/another-process-with-id-is-currently-running-ngcc)

**Comment by gkalpak** [comment]
Sorry, it is not clear what this issue is about 😕
The linked StackOverflow thread seems to have a way to get past the problem.

Also, in recent versions the lockfile operations have improved (e.g. in the default workflow ngcc is able to wait for other running instances to complete) and the error messages have been improved (so if you still run into an issue, you should get more actionable errors).

If you are still running into a problem with the latest version of Angular, you can look through the issues on [angular/angular](https://github.com/angular/angular) to see if the problem has been reported before and (if not) open a new issue there.
